[package]
name = "assembler"
version = "0.1.0"
authors = ["mopp <hello@mopp.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
